version: '3.8'

services:
  stories:
    build: . # Build with the Dockerfile here
    command: npm start # Run npm start as the command
    ports:
      - 3000:3000 # The app uses port 3000 by default, publish it as 3000
    volumes:
      - stories:/usr/src/app # Let us modify the contents of the container locally
      - node_modules:/usr/src/app/node_modules # A bit of node magic, this ensures the dependencies built for the image are not available locally.
    container_name: stories # Container name for convenience

  db:
    image: postgres:latest
    

volumes: # This is required for the node_modules named volume
  node_modules: