POST http://localhost:4000/trpc/createUser
content-type: application/json

{
    "bio": "Boring dude",
    "name": "Thomas5"
}


###
GET http://localhost:4000/trpc/getUserById
content-type: text/plain; charset=utf-8
//authorization: _e5_bv3vwnaZr4t7azr7W

"1655539355428"