name: Deploy # Name of the workflow

# On a push to the branch named master
on:
  push:
    branches:
      - main

jobs:
  publish-docker-hub:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # Checkout to the repository
      - uses: actions/checkout@v2

      # https://docs.docker.com/build/ci/github-actions/multi-platform/
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      # We need to login so we can later push the image without issues.
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Builds image
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: illispi/stories:latest
