name: Deploy # Name of the workflow

# On a push to the branch named main
on:
  push:
    branches:
      - main

jobs:
  publish-docker-hub:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    env:
      VITE_DISCORD_CLIENT_ID: 1122801938703065108
      VITE_AUTH_URL: https://stories.delvis.org
      VITE_SITE: https://stories.delvis.org

    steps:
      # Checkout to the repository
      - uses: actions/checkout@v4

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      # We need to login so we can later push the image without issues.
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Builds image
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: illispi/stories:latest
